on: [push, pull_request]
name: Test
jobs:
  test-linux:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Test
        run: go test ./...
      - name: Bench
        run: go test -benchmem -bench . ./...
  test-macos:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup loopback interface for tests
        run: |
          sudo ifconfig lo0 alias 127.0.0.2
          sudo ifconfig lo0 alias 127.0.0.11
          sudo ifconfig lo0 alias 127.0.0.12
      - name: Test
        run: go test ./...
      - name: Bench
        run: go test -benchmem -bench . ./...
  # test-windows:
  #   strategy:
  #     matrix:
  #       go-version: [1.12.x, 1.13.x]
  #   runs-on: windows-latest
  #   steps:
  #   - name: Install Go
  #     uses: actions/setup-go@v1
  #     with:
  #       go-version: ${{ matrix.go-version }}
  #   - name: Checkout code
  #     uses: actions/checkout@v1
  #   - name: Test
  #     run: go test ./...
  #   - name: Bench
  #     run: go test -benchmem -bench . ./...
